version: '3.8'

services:
  repository-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repository-monitor
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - TZ=Europe/Istanbul
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
